version: '3.8'
services:
  api:
    build: .
    ports:
      - "5001:5001"
    depends_on:
      - db
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
    command: sh -c "npm install && npx prisma migrate deploy && node index.js"
  
  worker:
    build: .
    depends_on:
      - db
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
    command: sh -c "npm install && npx prisma migrate deploy && node tasks/index.js"


  db:
    image: postgres
    environment:
      - POSTGRES_DB=google-scraper
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
